### ISSUE TITLE
failing at the git stuff

### ISSUE THREAD

**Issue by eliabieri** [eadf/esp_mqtt_lcd#1]
im really unexperienced in git and thats why i failed with the subtree and merging stuff.
Could you upload the pre merged repo somewhere?
I really want to try your amazing project!
thanks

**Comment by eadf** [comment]
Hm, it's suppose to be usable right out of the box. No assembly required. 
Maybe i made some mistakes. Ill check in to it.

If you use my makefile it should pull in the modules it needs from the subtrees, and skip the other parts (demo/test code).

Makefile:

```
MODULES= driver esp8266_pcd8544_subtree/driver/easygpio esp8266_pcd8544_subtree/driver/pcd8544 esp_mqtt_subtree/mqtt user
```

**Comment by eliabieri** [comment]
I get this error when I compile (make -f Makefile.mac):

CC driver/stdout.c
CC user/user_main.c
user/user_main.c:32:18: fatal error: mqtt.h: No such file or directory
 #include "mqtt.h"
                  ^
compilation terminated.
make: **\* [build/user/user_main.o] Error 1

So i think theres a problem with the merging somewhere.

**Comment by eadf** [comment]
Does your _MODULES_ variable (in the Makefile) contain _esp_mqtt_subtree/mqtt_ ?
I just re-cloned the entire project to a temp folder and it compiles ok

**Comment by eliabieri** [comment]
Ok i edited the MODULES line, but theres still an error:

CC esp_mqtt_subtree/mqtt/config.c
CC esp_mqtt_subtree/mqtt/mqtt.c
CC esp_mqtt_subtree/mqtt/mqtt_msg.c
CC esp_mqtt_subtree/mqtt/proto.c
CC esp_mqtt_subtree/mqtt/queue.c
CC esp_mqtt_subtree/mqtt/ringbuf.c
CC esp_mqtt_subtree/mqtt/utils.c
CC esp_mqtt_subtree/mqtt/wifi.c
CC user/user_main.c
user/user_main.c:40:29: fatal error: pcd8544/pcd8544.h: No such file or directory
 #include "pcd8544/pcd8544.h"
                             ^
compilation terminated.
make: **\* [build/user/user_main.o] Error 1

**Comment by eadf** [comment]
MODULES must contain these items:

```
MODULES= driver esp8266_pcd8544_subtree/driver/easygpio esp8266_pcd8544_subtree/driver/pcd8544 esp_mqtt_subtree/mqtt user
```

You should be able to use the supplied Makefile.mac.
Just set overrides in your environment (shell or eclipse) that corrects the default file locations to your preferences:
export SDK_BASE=/esptool/esp-open-sdk/sdk
export ESPTOOL=esptool.py
export ESPPORT=/dev/ttyUSB0 or sumething
and add the cross compiler binaries to your PATH

**Comment by eliabieri** [comment]
ok after a long time of trying it finally works now.
thank you

**Comment by eadf** [comment]
I just removed my cheat sheet so that nobody is tempted to execute it and messing up their local git repo.
I also renamed esp_mqtt_subtree to just mqtt (same with pcd8544). It was too messy.
Hope these changes doesn't affect your environment too much, now when you just got it running and all.
