### ISSUE TITLE
how can I change the MQTT port

### ISSUE THREAD

**Issue by morlac** [eadf/esp_mqtt_lcd#3]
Hi,
as the default-port for MQTT is 1883 [FAQ on mqtt.org](http://mqtt.org/faq) I want to change it, but so far all my changes in every src-file I found containing the port were unsuccessful.
After `make clean all flash` again port 1880 is used.

**Comment by eadf** [comment]
That's common problem/feature of [mqtt](https://github.com/tuanpmt/esp_mqtt).
To make the (mqtt related) properties in user_config.h to actually 'stick'. You will have to increment CFG_HOLDER in the same file. 

I suspect the intention is to be able to persistently change the mqtt configuration in runtime and CFG_HOLDER is there to prevent the chip from [re-flashing](http://en.wikipedia.org/wiki/Flash_memory#Memory_wear) itself on every boot up.

**Comment by morlac** [comment]
Thanks for this info. Now it makes sense to me.
